### ISSUE TITLE
Permitir a criação de subtasks

### ISSUE THREAD

**Issue by Tharllymartins** [Tharllymartins/doItNow.Api#3]
- [x]  Ajustar estrutura do back para permitir a criação de subtasks
- [x]  Criar rota e disponibilizar endpoint pro front criar uma subtask
- [x]  Criar rota e disponibilizar endpoint pro front atualizar os dados de uma task
